name: Build/release
on:
  push:
      # Sequence of patterns matched against refs/tags
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false
      
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install packages
        run: npm i

      - name: Install debian packager
        if: matrix.os == 'ubuntu-latest'
        run: npm i --save electron-installer-debian  

      - name: Build
        run: npm run build

      - name: Build/release Electron app
        if: matrix.os == 'ubuntu-latest'
        run: sudo npm run package-linux

      - name: Build/release Electron app
        if: matrix.os == 'macOS-latest'
        run: sudo npm run package
      
      - name: Build/release Electron app
        if: matrix.os == 'windows-latest'
        run: npm run package-win 

        
      - name: see directory
        run: ls -R ./release-builds

      - uses: montudor/action-zip@v0.1.0
        if: matrix.os == 'windows-latest'
        with:
          args: zip -qq -r ./windows.zip ./release-builds/win

      - name: Release-linux
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'windows-latest'
        with:
          files: ./windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

