name: Build/release
on:
  push:
      # Sequence of patterns matched against refs/tags
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false
      
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install packages
        run: npm i

      - name: Install debian packager
        if: matrix.os == 'ubuntu-latest'
        run: npm i --save electron-installer-debian  

      - name: Build
        run: npm run build

      - name: Build/release Electron app
        if: matrix.os == 'ubuntu-latest'
        run: sudo npm run package-linux && ls ./release-linux

      - name: Build/release Electron app
        if: matrix.os == 'ubuntu-latest'
        run: sudo npm run repackage-linux

      - name: Upload binaries to release linux
        uses: svenstaro/upload-release-action@v1-release
        if: matrix.os == 'ubuntu-latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./release-linux/l337*.deb
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          

      - name: Build/release Electron app
        if: matrix.os == 'macOS-latest'
        run: sudo npm run package && ls ./release-builds/mac
      
      - name: Build/release Electron app
        if: matrix.os == 'macOS-latest'
        run: sudo npm run create-dmg

      - name: Build/release Electron app
        if: matrix.os == 'windows-latest'
        run: npm run package-win && ls ./release-builds/win/l337-win32-x64
      

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        if: matrix.os == 'windows-latest'
        with:
          name: L337-win
          path: ./release-builds/win/l337-win32-x64

      - name: Upload binaries to release linux
        uses: svenstaro/upload-release-action@v1-release
        if: matrix.os == 'macOS-latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./L337.dmg
          asset_name: L337-Mac.dmg
          tag: ${{ github.ref }}
          overwrite: true