name: Build/release
on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install packages
        run: npm i

      - name: Build/release Electron app
        if: matrix.os == 'macOS-latest'
        run: npm run package
      
      - name: Build/release Electron app
        if: matrix.os == 'windows-latest'
        run: npm run package-win

      - name: Build/release Electron app
        if: matrix.os == 'ubuntu-latest'
        run: npm run package-linux